### ISSUE TITLE
Wrong delay on blinky example

### ISSUE THREAD

**Issue by anisse** [ch32-rs/ch58x-hal#6]
After trying the blinky and yd-ch582m examples on a YD-CH582M core board, the delay does not work as expected. It's about ~100 times too long, setting delay_ms to 10 gives a ~1s blink (I haven't measured exactly).

Maybe the clock setup is not correct?

I'm using wchisp as a runner/flasher.

**Comment by andelf** [comment]
Thanks for the report.
I'll check this soon.

Could you help print pac::SYSTICK.CNT values at a certain interval to check the system frequency?
(This is a known method to get the current sysclk freq reliably)

**Comment by anisse** [comment]
I have a wchlink but did not set it up yet, so I don't have a serial console. I'll try it and come back to you, but this might need some soldering first.

**Comment by anisse** [comment]
I have been unable to enable debugging on the chip with wchisp, I must have done something wrong at some point; I modified the reset value and rebuilt multiple times, but it always comes back to the same value (I realize this is out of scope of this bug). I am not sure if the 2-wire debugging is necessary to get serial output though.

**Comment by andelf** [comment]
I see. Could you try the release mode using `--release`?

**Comment by anisse** [comment]
You're correct, running in release mode, it does run at the correct speed. I was not able to enable the debug mode and flash something (verify fails), but this is something for another bug.

Thanks a lot!
